### ISSUE TITLE
Showing blank page after installing

### ISSUE THREAD

**Issue by configzone** [magepal/magento2-customeraccountlinksmanager#1]
Some reason after module installing in 2,2,1, shows blank page in admin. cant config anymore.

Does it known bug?

Thanks

**Comment by srenon** [comment]
Could you provide more information on your setup

- OS - (vagrant / if VM host and guest / etc)?
- PHP version?
- Was the module installed using composer or manually?
- Does path [root]/app/code/MagePal/CustomerAccountLinksManager exist?
- Does path [root]/vendor/magepal/magento2-customeraccountlinksmanager exist?
- Open [root]/composer.json, search for "magepal" did any match found?

Enabled php error and check if the error is similar to https://stackoverflow.com/questions/32475892/reflectionexception-class-classname-does-not-exist-laravel

**Comment by configzone** [comment]
HI Srenon,

Thanks for the reply. Please see below information as requested.

OS - (vagrant / if VM host and guest / etc)?
CENTSO 7

PHP version?
PHP 7.0.26

Was the module installed using composer or manually?
Tried both

Does path [root]/app/code/MagePal/CustomerAccountLinksManager exist?
After installing without composer - Yes

Does path [root]/vendor/magepal/magento2-customeraccountlinksmanager exist?
After installing with composer - Yes

Open [root]/composer.json, search for "magepal" did any match found?
can see this =         "magepal/magento2-customeraccountlinksmanager": "^1.1"

Please see screenshot for your note.

Thanks

![blank-error](https://user-images.githubusercontent.com/10284957/34329384-b5efa7b4-e962-11e7-8604-51bea9a0945d.png)

**Comment by srenon** [comment]
Do all these 3 things exist now?

Does path [root]/app/code/MagePal/CustomerAccountLinksManager exist?
After installing without composer - Yes

Does path [root]/vendor/magepal/magento2-customeraccountlinksmanager exist?
After installing with composer - Yes

Open [root]/composer.json, search for "magepal" did any match found?

**Comment by configzone** [comment]
HI Srenon,

Currently, after using composer, we have status.

Does path [root]/app/code/MagePal/CustomerAccountLinksManager exist?
NO

Does path [root]/vendor/magepal/magento2-customeraccountlinksmanager exist?
YES

Open [root]/composer.json, search for "magepal" did any match found?
YES

**Comment by srenon** [comment]
Not sure why but this has something to do with the module sequence. Also,  I can only replicate it when install using composer.

Try, editing vendor/magepal/magento2-customeraccountlinksmanager/etc/module.xml and add `<module name="Magento_Wishlist"/>`

See

```<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MagePal_CustomerAccountLinksManager" setup_version="1.0.3">
        <sequence>
            <module name="Magento_Customer"/>
            <module name="Magento_Wishlist"/>
        </sequence>
    </module>
</config>```

Let me know if this work for you and I will update this module.

**Comment by configzone** [comment]
Hi Srenon, I have tried that but does not help. Seems like the issue was from the theme, as I have recently upgraded and all resolved. I appreciate for all your help.
