### ISSUE TITLE
Page title position on customer frontend

### ISSUE THREAD

**Issue by Kaputz** [magepal/magento2-customeraccountlinksmanager#2]
When I login with a customer, if this module is installed the page title shows at the bottom of the screen.

This problem is visible in your screenshots:
https://cloud.githubusercontent.com/assets/1415141/25233635/8354aa4e-25ad-11e7-87ae-55fcee1a4194.png

As there is no Layout file in this module, I have no idea on what's causing this or how to fix it.

This was installed via composer and the server is running: 
Ubuntu Server 16.04 on a VDC with PHP 7.0 and Apache2 with Varnish, and is on production.

**Comment by srenon** [comment]
What version of Magento are you using?

I just tested on 2.1.9 

If I remember correctly this was a core template issue in earlier versions.

![image](https://user-images.githubusercontent.com/1415141/34304296-34f2fe5c-e707-11e7-9526-0142bffbd4f7.png)

**Comment by Kaputz** [comment]
I'm using Magento 2.1.11.

Steps to reproduce:
1. Create new magento 2.1.11 with: $ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.1.11 .
2. Install M2 with: $ bin/magento setup:install ...
2. Install customeraccountlinksmanager: $ composer require magepal/magento2-customeraccountlinksmanager
3. Login with a customer (i used n98-magerun2 to quickly create a customer in CLI)

Expected:
1. Frontend OK.

Result:
1. Title shows on the bottom of the page.

**Comment by srenon** [comment]
Can you disable the module, retest and post a screenshot

**Comment by Kaputz** [comment]
BEFORE:
![2](https://user-images.githubusercontent.com/34772855/34306192-d580683c-e739-11e7-9492-d2cdab80c28f.jpg)

AFTER:
$ composer remove magepal/magento2-customeraccountlinksmanager
![3](https://user-images.githubusercontent.com/34772855/34306195-da4b116e-e739-11e7-87b0-835ea089089b.jpg)

PS: Between the module installs and uninstalls, i always do setup:upgrade, cache:flush, di:compile and deploy:static to update the files.

**Comment by Kaputz** [comment]
Another shop (the one on production)
BEFORE:
![l1](https://user-images.githubusercontent.com/34772855/34306326-7c23085c-e73a-11e7-8b12-4b8dc41cf9da.png)

AFTER:
$ composer remove magepal/magento2-customeraccountlinksmanager
![l2](https://user-images.githubusercontent.com/34772855/34306334-82aa32ea-e73a-11e7-995a-b969f238054c.png)

**Comment by Kaputz** [comment]
Ok, been doing some more testing and it seems i had one more module on both shops: magepal/magento2-gmailsmtpapp

The problem seems to be related to having these 2 modules at the same time.
If i remove either of them, the shop works as intended.

**Comment by srenon** [comment]
I tried several different tests but cannot replicate the issue.

can you add the configuration you have in core_config_data. 

>select * from core_config_data where path like 'customeraccountlinksmanager%'

**Comment by Kaputz** [comment]
Did you try adding the module I suggested in my last post? I think it's one of your other modules:
$ composer require magepal/magento2-gmailsmtpapp
I did several tests and I can always reproduce the issue if both are enabled at the same time. As soon as I remove either one or the other, the issue disappears. 
As for the configs in the table, I don't have access to that Database right now, but they should be easy to reproduce by looking at the screenshot (see the options that are not disabled).
As for the other module, no configs are required to reproduce the issue, just install, do the usual recompile and you should be able to see it.
I'll post again with the configs when I get back to the office, if you still require them by then.

**Comment by srenon** [comment]
Yea, I tried with only those 2 modules installed

I also tried with all the modules that should have been installed when I made the original screenshot

Can you run the command below to list all custom modules you have installed

$ php bin/magento module:status | grep -v Magento_
List of enabled modules:
MagePal_GoogleTagManager
MagePal_CustomerAccountLinksManager
MagePal_GmailSmtpApp
MagePal_CustomDeliveryDateRate

**Comment by Kaputz** [comment]
Here are the screenshots of that command

With only 1 module:
![1](https://user-images.githubusercontent.com/34772855/34355054-82898c0a-ea2a-11e7-9e19-693910eaa5e7.jpg)

With both:
![2](https://user-images.githubusercontent.com/34772855/34355058-8dabf1ea-ea2a-11e7-8b09-0ebb65566854.jpg)

Now with only the other module, just for the record:
![3](https://user-images.githubusercontent.com/34772855/34355107-edf2b0ca-ea2a-11e7-81c0-97b6d52aad1f.jpg)

The EXACT commands i'm using
To add:
composer require magepal/magento2-gmailsmtpapp
composer require magepal/magento2-customeraccountlinksmanager
To remove:
composer remove magepal/magento2-gmailsmtpapp
composer remove magepal/magento2-customeraccountlinksmanager
To apply the changes:
bin/magento setup:upgrade (tried today, this one is enough)

Also for the record, here are the configs you requested from the database:
config_id;scope;scope_id;path;value
112;default;0;customeraccountlinksmanager/general/active;1
113;default;0;customeraccountlinksmanager/general/action;1
114;default;0;customeraccountlinksmanager/general/sections;"customer-account-navigation-downloadable-products-link,customer-account-navigation-wish-list-link,customer-account-navigation-newsletter-subscriptions-link,customer-account-navigation-product-reviews-link,customer-account-navigation-billing-agreements-link"

**Comment by srenon** [comment]
Not sure why but this has something to do with the module sequence. Also,  I can only replicate it when install using composer.

Try, editing vendor/magepal/magento2-customeraccountlinksmanager/etc/module.xml and add `<module name="Magento_Wishlist"/>`

Eg
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MagePal_CustomerAccountLinksManager" setup_version="1.0.3">
        <sequence>
            <module name="Magento_Customer"/>
            <module name="Magento_Wishlist"/>
        </sequence>
    </module>
</config>
```


Let me know if this work for you and I will update this module.

**Comment by Kaputz** [comment]
That fixed it for me, thank you.

**Comment by srenon** [comment]
@Kaputz ... Thanks for your help debugging.
