### ISSUE TITLE
non-object from $configXml->body->referenceContainer

### ISSUE THREAD

**Issue by Amadeco** [magepal/magento2-customeraccountlinksmanager#3]
Good evening,

I have just installed your extension on our staging website, enabled, and navigate through admin back-office, but we meet casualties :

> Exception #0 (Exception): Notice: Trying to get property of non-object in /home/artbambou/public_html/new/vendor/magepal/magento2-customeraccountlinksmanager/Model/Config/Source/Sections.php on line 50

This instruction doesn't seems to be in our xml files (maybe overwritten in a custom layout file, not sure though).

For now, we have corrected to check if $configXml->body->referenceContainer is populated.

new code ::

`<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace MagePal\CustomerAccountLinksManager\Model\Config\Source;

class Sections implements \Magento\Framework\Option\ArrayInterface
{
    /** @var \Magento\Framework\App\Utility\Files  */
    protected $utilityFiles;

    protected $links;

    public function __construct(
        \Magento\Framework\App\Utility\Files $utilityFiles,
        \Magento\Framework\View\Element\Html\Links $links
    ) {
        $this->utilityFiles = $utilityFiles;
        $this->links = $links;
    }
    /**
     * @return array
     */
    public function toOptionArray()
    {
        return $this->getSections();
    }

    public function getSections()
    {
        $fileList = $this->utilityFiles->getLayoutFiles(['area_name' => 'frontend'], false);

        $list = [];

        foreach ($fileList as $configFile) {
            if (strpos($configFile, 'customer_account.xml') !== false) {
                $configXml = simplexml_load_file($configFile);

                if ($referenceBlocks = $configXml->body->referenceBlock) {
                    foreach ($referenceBlocks as $referenceBlock) {
                        if (!empty($referenceBlock->xpath('block/arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceBlock->block['name']] = [
                                'value' => (string) $referenceBlock->block['name'],
                                'label' => (string) $referenceBlock->xpath('block/arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                } elseif ($referenceContainerBlocks = $configXml->body->referenceContainer->block->block->block) {
                    for ($count = 0; $count < count($referenceContainerBlocks); $count++) {
                        if (!empty($referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceContainerBlocks[$count]['name']] = [
                                'value' => (string) $referenceContainerBlocks[$count]['name'],
                                'label' => (string) $referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                } elseif ($referenceContainerBlocks = $configXml->body->referenceContainer->block->block) {
                    for ($count = 0; $count < count($referenceContainerBlocks); $count++) {
                        if (!empty($referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceContainerBlocks[$count]['name']] = [
                                'value' => (string) $referenceContainerBlocks[$count]['name'],
                                'label' => (string) $referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                }
            }
        }

        return $list;
    }
}
`

Not the best way to do that,

I will think in a better way later.

I want to warn you about this error.

Thank you to kindly dispose your code,

Regards,

Ilan PARMENTIER

**Comment by Amadeco** [comment]
Maybe something like this : 

```
<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace MagePal\CustomerAccountLinksManager\Model\Config\Source;

class Sections implements \Magento\Framework\Option\ArrayInterface
{
    /** @var \Magento\Framework\App\Utility\Files  */
    protected $utilityFiles;

    protected $links;

    public function __construct(
        \Magento\Framework\App\Utility\Files $utilityFiles,
        \Magento\Framework\View\Element\Html\Links $links
    ) {
        $this->utilityFiles = $utilityFiles;
        $this->links = $links;
    }
    /**
     * @return array
     */
    public function toOptionArray()
    {
        return $this->getSections();
    }

    public function getSections()
    {
        $fileList = $this->utilityFiles->getLayoutFiles(['area_name' => 'frontend'], false);

        $list = [];

        foreach ($fileList as $configFile) {
            if (strpos($configFile, 'customer_account.xml') !== false) {
                $configXml = simplexml_load_file($configFile);

                if ($referenceBlocks = $configXml->body->referenceBlock) {
                    foreach ($referenceBlocks as $referenceBlock) {
                        if (!empty($referenceBlock->xpath('block/arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceBlock->block['name']] = [
                                'value' => (string) $referenceBlock->block['name'],
                                'label' => (string) $referenceBlock->xpath('block/arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                }
                
                if (! isset($configXml->body->referenceContainer)) {
	                continue;
                }
                
                if ($referenceContainerBlocks = $configXml->body->referenceContainer->block->block->block) {
                    for ($count = 0; $count < count($referenceContainerBlocks); $count++) {
                        if (!empty($referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceContainerBlocks[$count]['name']] = [
                                'value' => (string) $referenceContainerBlocks[$count]['name'],
                                'label' => (string) $referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                } elseif ($referenceContainerBlocks = $configXml->body->referenceContainer->block->block) {
                    for ($count = 0; $count < count($referenceContainerBlocks); $count++) {
                        if (!empty($referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]'))) {
                            $list[(string) $referenceContainerBlocks[$count]['name']] = [
                                'value' => (string) $referenceContainerBlocks[$count]['name'],
                                'label' => (string) $referenceContainerBlocks[$count]->xpath('arguments/argument[@name="label"]')[0]
                            ];
                        }
                    }
                }
            }
        }

        return $list;
    }
}
```

**Comment by srenon** [comment]
@mageho ... Please open a Pull Request and I will review your changes

**Comment by Amadeco** [comment]
Sorry for the late answer, I am not familiar with Github, next time, I will proceed this way. Thank you for the fix and for the extension.
