### ISSUE TITLE
it's don't show config screen when used with Magento 2.2.5

### ISSUE THREAD

**Issue by joomlacorner** [magepal/magento2-customeraccountlinksmanager#4]
it's don't show anything in admin when used with Magento 2.2.5

![screen shot 2561-08-30 at 01 32 06](https://user-images.githubusercontent.com/144291/44807877-e0ff5580-abf4-11e8-9837-4f4d9a103403.png)

**Comment by srenon** [comment]
Try cleaning cache... no known issue in 2.2.5

![image](https://user-images.githubusercontent.com/1415141/44808336-f98e5200-ab99-11e8-831a-688440846c42.png)

**Comment by srenon** [comment]
Check your error log

**Comment by joomlacorner** [comment]
@srenon  my error in system.log 
[2018-08-29 19:03:31] main.CRITICAL: Notice: Trying to get property of non-object in /home/devmag/public_html/app/code/MagePal/CustomerAccountLinksManager/Model/Config/Source/Sections.php on line 57 [] []

**Comment by srenon** [comment]
@joomlacorner ... replace your local content of Model/Config/Source/Sections.php with https://github.com/magepal/magento2-customer-account-links-manager/blob/master/Model/Config/Source/Sections.php and if that work then I will release a new version

**Comment by joomlacorner** [comment]
@srenon it's worked!  
thank you very much.

**Comment by srenon** [comment]
This issue is now fixed in Version 1.1.5. 

Thanks for choosing Magepal Extension.
www.magepal.com
